# Generated by Django 4.2 on 2024-06-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsapp.item')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsapp.user')),
            ],
        ),
    ]
